spring.application.name=backend

#spring.datasource.url=jdbc:mysql://localhost:3306/jobBoard_db
#spring.datasource.username=root
#spring.datasource.password=root

spring.datasource.url=postgresql://job_board_user:4U44YXbT9fziwGcgvYOfqMXGpDUTTN2q@dpg-d9j6rrjtqb8s739sit90-a.oregon-postgres.render.com/job_board_db_x1pf
spring.datasource.username=job_board_user
spring.datasource.password=4U44YXbT9fziwGcgvYOfqMXGpDUTTN2q

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


